name: linos_dictionary
description: A dictionary of unusual and intriguing phrases of the English language, sorted into different topics.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: "1.20.4"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.1+2
  firebase_admob: ^0.10.0+1
  firebase_core: ^0.5.0
  firebase_crashlytics: ^0.2.1
  flutter_bloc: ^6.0.5
  flutter_dotenv: ^2.1.0
  recase: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
