name: linos_dictionary
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: "1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.3+2
  cloud_firestore: ^0.13.0+1
  firebase_admob: ^0.9.0+10
  recase: ^3.0.0
  flutter_dotenv: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env