name: linos_dictionary
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: "1.17.2"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^5.0.1
  cloud_firestore: ^0.13.6
  firebase_admob: ^0.9.3+2
  firebase_core: ^0.4.5
  firebase_crashlytics: ^0.1.3+3
  flutter_bloc: ^5.0.1
  flutter_dotenv: ^2.1.0
  recase: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
